#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

payload = { 'key' : 'value' }
r = requests.post(url, data=payload, files=dict(firstname='doge',lastname='mcpie'))

print r.status_code
print r.text


